#!/usr/bin/env -S bash -i
#!/bin/sh

abs_top_srcdir="`cd "/home/ANT.AMAZON.COM/rodnchr/Documents/genpro" > /dev/null; pwd`"
abs_top_builddir="`cd "/home/ANT.AMAZON.COM/rodnchr/Documents/genpro" > /dev/null; pwd`"

GUILE_LOAD_COMPILED_PATH="$abs_top_builddir${GUILE_LOAD_COMPILED_PATH:+:}$GUILE_LOAD_COMPILED_PATH"
GUILE_LOAD_PATH="$abs_top_builddir:$abs_top_srcdir${GUILE_LOAD_PATH:+:}:$GUILE_LOAD_PATH"
export GUILE_LOAD_COMPILED_PATH GUILE_LOAD_PATH

PATH="$abs_top_builddir:$PATH"
export PATH

exec "$@"
